-- Canon Character Database Integration SQL
-- Twin Academy Worlds Card Game - Four Core Characters
-- Generated by card-game-designer agent

-- Insert missing dimensions first (assuming they don't exist yet)
INSERT INTO dimensions (id, name, physics_type, description) VALUES 
(1, 'Nankatsu', 'harmony', 'Team harmony amplifies individual abilities exponentially'),
(2, 'Camelot', 'focus', 'Individual mental clarity unlocks supernatural precision'),
(3, 'Nexus', 'hybrid', 'Interdimensional bridge combining both physics systems')
ON CONFLICT (id) DO NOTHING;

-- Insert base characters (assuming they don't exist)
INSERT INTO characters (id, name, japanese_name, series, debut_year, character_archetype, power_level) VALUES
(1, 'Tsubasa Ozora', '大空翼', 'Captain Subasa', 1981, 'protagonist', 85),
(2, 'Genzo Wakabayashi', '若林源三', 'Captain Subasa', 1981, 'rival', 90),
(3, 'Gawain Nanaumi', '七海ガウェイン', 'Rising Impact', 1998, 'protagonist', 80),
(4, 'Lancelot Norman', 'ランスロット・ノーマン', 'Rising Impact', 1998, 'rival', 85)
ON CONFLICT (id) DO NOTHING;

-- Insert character variants (Canon versions)
INSERT INTO character_variants (
    base_character_id, variant_type, variant_name, source_dimension_id,
    power_stat, speed_stat, precision_stat, harmony_stat, focus_stat,
    card_rarity, card_cost, collection_number,
    adapted_backstory, created_at
) VALUES
-- Tsubasa Ozora Canon
(1, 'canon', 'Tsubasa Ozora', 1, 65, 85, 80, 100, 60, 'legendary', 8, 'TAW001-001',
'The soccer prodigy from Nankatsu Elementary whose motto "the ball is my friend" embodies perfect harmony between player and sport. Natural leader who inspires teammates through unwavering optimism and incredible aerial techniques.',
CURRENT_TIMESTAMP),

-- Genzo Wakabayashi Canon  
(2, 'canon', 'Genzo Wakabayashi', 1, 80, 95, 90, 70, 85, 'legendary', 7, 'TAW001-002',
'The legendary SGGK (Super Great Goal Keeper) whose declaration "My goal will never be broken!" drove him to achieve defensive perfection. Evolved from isolated rival to loyal teammate while maintaining uncompromising excellence.',
CURRENT_TIMESTAMP),

-- Gawain Nanaumi Canon
(3, 'canon', 'Gawain Nanaumi', 2, 90, 60, 65, 35, 80, 'legendary', 8, 'TAW001-003',
'Country boy from Fukushima with supernatural golf driving ability. His Rising Impact gift allows 450-yard drives that defy physics through pure determination and mountain-forged strength.',
CURRENT_TIMESTAMP),

-- Lancelot Norman Canon
(4, 'canon', 'Lancelot Norman', 2, 45, 55, 100, 30, 95, 'legendary', 7, 'TAW001-004',
'Perfectionist putting master whose Shining Road gift reveals golden paths to victory. Elegant precision and unwavering mental focus make him nearly unbeatable in accuracy-based competition.',
CURRENT_TIMESTAMP);

-- Insert base techniques
INSERT INTO techniques (
    name, japanese_name, base_character_id, technique_category, dimension_origin_id,
    canonical_description, created_at
) VALUES
-- Tsubasa Techniques
('Drive Shot', 'ドライブシュート', 1, 'special_move', 1, 'Signature shooting technique using forward spin to create unpredictable trajectory', CURRENT_TIMESTAMP),
('Overhead Kick', 'オーバーヘッドキック', 1, 'special_move', 1, 'Acrobatic aerial technique allowing shots, passes, and defensive plays while airborne', CURRENT_TIMESTAMP),
('Golden Combi Attack', 'ゴールデンコンビ', 1, 'special_move', 1, 'Perfect combination technique with Taro Misaki demonstrating ultimate team harmony', CURRENT_TIMESTAMP),
('Skywing Shot', 'スカイウイングシュート', 1, 'special_move', 1, 'Ultimate technique taught by Roberto, low trajectory becoming high near goal', CURRENT_TIMESTAMP),

-- Genzo Techniques
('SGGK', 'スーパーグレートゴールキーパー', 2, 'special_move', 1, 'Foundation defensive technique combining superhuman reflexes with perfect positioning', CURRENT_TIMESTAMP),
('SGGK Catch', 'SGGKキャッチ', 2, 'special_move', 1, 'Advanced variant focusing on possession control rather than deflection', CURRENT_TIMESTAMP),
('SGGK Perfect', 'SGGKパーフェクト', 2, 'special_move', 1, 'Ultimate evolution incorporating European techniques with Japanese innovation', CURRENT_TIMESTAMP),
('Counter Attack Launch', 'カウンターアタック', 2, 'special_move', 1, 'Transforms defensive saves into immediate offensive opportunities', CURRENT_TIMESTAMP),

-- Gawain Techniques  
('Rising Impact', 'ライジングインパクト', 3, 'gift', 2, 'Supernatural ability to achieve perfect sweet spot impact for 450-yard drives', CURRENT_TIMESTAMP),
('Explosion Spin', 'エクスプロージョンスピン', 3, 'special_move', 2, 'Devastating technique causing explosive ball impact that tears up the green', CURRENT_TIMESTAMP),
('Phoenix Awakening', 'フェニックス覚醒', 3, 'special_move', 2, 'Transformation into fierce competitive state under extreme pressure', CURRENT_TIMESTAMP),
('Grandfather\'s Strength', '祖父の力', 3, 'basic_skill', 2, 'Mountain-forged power from years of forestry work and rural training', CURRENT_TIMESTAMP),

-- Lancelot Techniques
('Shining Road', '月の導き', 4, 'gift', 2, 'Supernatural putting ability revealing golden path to perfect accuracy', CURRENT_TIMESTAMP),
('Perfectionist\'s Strike', 'パーフェクトストライク', 4, 'special_move', 2, 'Elite technique demanding flawless execution for maximum effectiveness', CURRENT_TIMESTAMP),
('Analytical Mastery', '分析マスタリー', 4, 'special_move', 2, 'Complete course reading and strategic planning ability', CURRENT_TIMESTAMP),
('Sister\'s Dream', 'シスターズドリーム', 4, 'special_move', 2, 'Emotional drive technique powered by love for sister Kajury', CURRENT_TIMESTAMP);

-- Insert technique variants with game mechanics
INSERT INTO technique_variants (
    base_technique_id, character_variant_id, variant_name, adapted_description,
    technique_type, dimension_physics, energy_cost, base_damage,
    special_effects, target_type, range_type, created_at
) VALUES
-- Tsubasa Technique Variants
(1, 1, 'Drive Shot', 'Signature shooting technique with impossible spin trajectory', 'primary', 'harmony', 4, 75, 
'{"accuracy_bonus": 20, "spin_effect": 15, "team_combo": 25}', 'single', 'long', CURRENT_TIMESTAMP),

(2, 1, 'Overhead Kick', 'Acrobatic aerial technique for multiple situations', 'secondary', 'harmony', 3, 60,
'{"aerial_bonus": 30, "defensive_use": true, "golden_combi": 40}', 'flexible', 'close', CURRENT_TIMESTAMP),

(3, 1, 'Golden Combi Attack', 'Ultimate team combination technique', 'ultimate', 'harmony', 6, 95,
'{"requires_teammate": true, "unblockable_threshold": 150, "energy_restore": 2}', 'single', 'medium', CURRENT_TIMESTAMP),

(4, 1, 'Skywing Shot', 'Master technique from Roberto\'s teachings', 'primary', 'harmony', 5, 85,
'{"trajectory_change": true, "anti_defense": 25, "mentor_bonus": 20}', 'single', 'long', CURRENT_TIMESTAMP),

-- Genzo Technique Variants
(5, 2, 'SGGK', 'Foundation defensive technique with unbreakable will', 'primary', 'hybrid', 3, 0,
'{"defense_value": 85, "stacking_bonus": 15, "immunity": "intimidation"}', 'self', 'goal_area', CURRENT_TIMESTAMP),

(6, 2, 'SGGK Catch', 'Perfect possession control defensive technique', 'secondary', 'harmony', 4, 0,
'{"defense_value": 100, "possession_gain": true, "team_boost": 20}', 'incoming', 'extended_goal', CURRENT_TIMESTAMP),

(7, 2, 'SGGK Perfect', 'Ultimate evolution of defensive mastery', 'ultimate', 'focus', 6, 0,
'{"defense_value": 120, "multi_attack": true, "combo_defense": 25}', 'all_incoming', 'full_field', CURRENT_TIMESTAMP),

(8, 2, 'Counter Attack Launch', 'Instant transition from defense to offense', 'support', 'harmony', 2, 0,
'{"immediate_counter": true, "accuracy_bonus": 40, "leadership": 10}', 'friendly', 'full_field', CURRENT_TIMESTAMP),

-- Gawain Technique Variants
(9, 3, 'Rising Impact', 'Supernatural sweet spot mastery for maximum distance', 'primary', 'focus', 4, 100,
'{"focus_accuracy": 25, "range_ignore": true, "power_scaling": 10}', 'single', 'long', CURRENT_TIMESTAMP),

(10, 3, 'Explosion Spin', 'Destructive power technique with area effect', 'primary', 'focus', 5, 85,
'{"area_damage": 20, "terrain_destroy": true, "accuracy_penalty": -15}', 'single_area', 'medium', CURRENT_TIMESTAMP),

(11, 3, 'Phoenix Awakening', 'Transformation into ultimate competitive state', 'ultimate', 'focus', 6, 0,
'{"stat_boost": 25, "duration": 3, "energy_reduction": 1, "immunity": "mental"}', 'self', 'self', CURRENT_TIMESTAMP),

(12, 3, 'Grandfather\'s Strength', 'Rural heritage power enhancement', 'support', 'focus', 3, 0,
'{"power_boost": 30, "focus_boost": 20, "environmental_immunity": true}', 'self_or_ally', 'close', CURRENT_TIMESTAMP),

-- Lancelot Technique Variants
(13, 4, 'Shining Road', 'Golden path vision for perfect putting accuracy', 'primary', 'focus', 3, 0,
'{"accuracy": 100, "mental_clarity": 25, "range_extend": 10, "ignore_penalties": true}', 'any', 'focus_range', CURRENT_TIMESTAMP),

(14, 4, 'Perfectionist\'s Strike', 'Elite technique demanding flawless execution', 'primary', 'focus', 4, 80,
'{"precision_scaling": 0.5, "critical_chance": 25, "pride_bonus": 30}', 'single', 'medium', CURRENT_TIMESTAMP),

(15, 4, 'Analytical Mastery', 'Complete field analysis and control', 'ultimate', 'focus', 5, 0,
'{"reveal_all": true, "negate_environment": true, "accuracy_boost": 20, "mental_pressure": 2}', 'field', 'global', CURRENT_TIMESTAMP),

(16, 4, 'Sister\'s Dream', 'Emotional transcendence for ultimate performance', 'ultimate', 'focus', 6, 0,
'{"stat_boost": 20, "invulnerability": true, "focus_boost": 15, "reward_double": true}', 'field_wide', 'global', CURRENT_TIMESTAMP);

-- Insert cards linking to character variants
INSERT INTO cards (
    card_set_id, character_variant_id, card_name, card_number, card_type,
    rarity, cost, card_effects, flavor_text, created_at
) VALUES
-- Tsubasa Card
(1, 1, 'Tsubasa Ozora - Soccer Prodigy', '001/200', 'character', 'legendary', 8,
'{"leadership": {"captain_inspiration": "+10 all stats to friendly characters", "harmony_discount": "-1 energy for harmony techniques", "sacrifice_restore": "3 energy to any teammate"}}',
'The ball is my friend, but my team makes me strong!', CURRENT_TIMESTAMP),

-- Genzo Card
(1, 2, 'Genzo Wakabayashi - SGGK Legend', '002/200', 'character', 'legendary', 7,
'{"goalkeeper": {"absolute_defense": "+25 defense in goal area", "protection_designation": "prevent direct targeting", "rival_bond": "+15 all stats with Tsubasa"}}',
'This is my domain. Nothing passes through!', CURRENT_TIMESTAMP),

-- Gawain Card
(1, 3, 'Gawain Nanaumi - Country Prodigy', '003/200', 'character', 'legendary', 8,
'{"gift_mastery": {"rising_impact": "+15 accuracy for power techniques", "optimal_vision": "see defensive weaknesses", "growth_potential": "+1 stat per successful technique (max +10)"}}',
'This power comes from the mountains, the forests, and my grandfather\'s love!', CURRENT_TIMESTAMP),

-- Lancelot Card
(1, 4, 'Lancelot Norman - Precision Master', '004/200', 'character', 'legendary', 7,
'{"elite_gift": {"shining_mastery": "auto-succeed vs precision <90", "intention_read": "reveal opponent next technique", "perfectionist": "+5 stats per consecutive success (max +25)"}}',
'The path to perfection is illuminated - all that remains is to walk it flawlessly.', CURRENT_TIMESTAMP);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_character_variants_canon ON character_variants(variant_type) WHERE variant_type = 'canon';
CREATE INDEX IF NOT EXISTS idx_technique_variants_canon ON technique_variants(character_variant_id) WHERE character_variant_id IN (1,2,3,4);
CREATE INDEX IF NOT EXISTS idx_cards_canon ON cards(character_variant_id) WHERE character_variant_id IN (1,2,3,4);

-- Update card set with accurate canon character count
UPDATE card_sets SET 
    legendary_count = 4,
    total_cards = 200
WHERE set_code = 'TAW001';

-- Verification queries (commented out for production)
/*
-- Verify character variants
SELECT cv.variant_name, cv.power_stat, cv.speed_stat, cv.precision_stat, cv.harmony_stat, cv.focus_stat, cv.card_cost
FROM character_variants cv WHERE cv.variant_type = 'canon' ORDER BY cv.base_character_id;

-- Verify technique variants  
SELECT c.name, tv.variant_name, tv.energy_cost, tv.base_damage, tv.technique_type
FROM technique_variants tv 
JOIN techniques t ON tv.base_technique_id = t.id
JOIN characters c ON t.base_character_id = c.id
WHERE tv.character_variant_id IN (1,2,3,4)
ORDER BY c.name, tv.energy_cost;

-- Verify cards
SELECT c.card_name, c.card_number, c.rarity, c.cost, c.flavor_text
FROM cards c WHERE c.character_variant_id IN (1,2,3,4) ORDER BY c.card_number;
*/