-- Import Core Canon Characters to Twin Academy Worlds Database
-- Generated by systematic agent deployment

-- Insert Core Characters
INSERT INTO characters (name, japanese_name, series_id, primary_dimension_id, age, grade_level, position, character_type, first_appearance_chapter, first_appearance_volume, description, personality_traits) VALUES 
('Tsubasa Ozora', '大空翼', 1, 1, 11, 'Elementary 6th Grade', 'Midfielder/Forward', 'protagonist', 1, 1, 'The heart and soul of Captain Subasa, Tsubasa Ozora is a soccer prodigy whose love for the game transcends mere competition. From his first appearance, he demonstrates an almost supernatural connection to soccer, viewing the ball as his closest friend. His signature Drive Shot and mastery of the Golden Combi with Taro Misaki showcase his technical brilliance, while his natural leadership and ability to inspire teammates represent the embodiment of Nankatsu Dimension''s team harmony philosophy. Tsubasa''s character development spans from an enthusiastic elementary school player to a world-class professional, always maintaining his pure joy for the beautiful game and his unwavering belief that soccer can bring people together across all boundaries.', ARRAY['Leadership', 'Optimism', 'Team-oriented', 'Persistent', 'Inspiring']),

('Genzo Wakabayashi', '若林源三', 1, 1, 11, 'Elementary 6th Grade', 'Goalkeeper', 'rival', 2, 1, 'The legendary SGGK (Super Great Goal Keeper), Genzo Wakabayashi represents the pinnacle of goalkeeping excellence in the Captain Subasa universe. Initially introduced as Tsubasa''s primary rival, Genzo''s character arc showcases one of manga''s most compelling transformations from arrogant prodigy to humble team leader. His SGGK technique series demonstrates supernatural reflexes and shot-stopping ability that defies physical limitations, while his intellectual approach to the game and strategic mindset make him invaluable beyond pure athleticism. Through his German training arc and international development, Genzo evolves from a individual-focused perfectionist to a goalkeeper who understands that true strength comes from protecting and elevating his entire team, embodying both defensive mastery and leadership excellence.', ARRAY['Perfectionist', 'Intelligent', 'Competitive', 'Loyal', 'Protective']),

('Gawain Nanaumi', '七海ガウェイン', 2, 2, 8, 'Elementary 3rd Grade', 'Golf Prodigy', 'protagonist', 1, 1, 'The protagonist of Rising Impact and embodiment of Camelot Dimension''s individual mastery philosophy, Gawain Nanaumi is a third-grade golf prodigy whose "Rising Impact" Gift allows him to achieve perfect contact for 450-yard drives that defy conventional physics. Despite his supernatural abilities, Gawain maintains remarkable humility and genuine love for golf that drives his continuous improvement. His character development at Camelot Academy showcases the tension between individual excellence and team support, as he learns to balance personal achievement with helping others reach their potential. Gawain''s relationship with his grandfather, his rivalry with Lancelot Norman, and his mentorship under various professionals demonstrate how individual mastery can enhance rather than diminish meaningful connections with others.', ARRAY['Humble', 'Determined', 'Talented', 'Respectful', 'Growth-minded']),

('Lancelot Norman', 'ランスロット・ノーマン', 2, 2, 8, 'Elementary 3rd Grade', 'Elite Golfer', 'rival', 3, 1, 'The precision master of Rising Impact and exemplar of technical excellence, Lancelot Norman possesses the supernatural "Shining Road" ability that allows him to visualize the perfect putting path and achieve accuracy across distances up to 70 yards. Initially appearing as an elite prodigy who transfers between academies seeking the ultimate competition, Lancelot''s character development reveals deep complexity beneath his perfectionist exterior. His relationship with his sister Kajury, whose eye injury influences his pursuit of excellence, adds emotional depth to his technical mastery. Through his rivalry and eventual friendship with Gawain Nanaumi, Lancelot learns that true precision comes not just from individual skill but from understanding and supporting others, making him a perfect representative of how Camelot Dimension''s focus philosophy can evolve to encompass meaningful relationships.', ARRAY['Perfectionist', 'Analytical', 'Caring', 'Precise', 'Evolving']);

-- Insert Character Academy Affiliations
INSERT INTO character_academies (character_id, academy_id, role, is_active) VALUES 
(1, 1, 'captain', true),  -- Tsubasa at Nankatsu Elementary
(2, 2, 'goalkeeper', true),  -- Genzo at Shutetsu Elementary 
(3, 2, 'student', true),  -- Gawain at Camelot Academy
(4, 2, 'student', true);  -- Lancelot at Camelot Academy

-- Insert Character Abilities
INSERT INTO abilities (name, japanese_name, character_id, ability_type, dimension_origin_id, description, first_used_chapter, mastery_level) VALUES 
('Drive Shot', 'ドライブシュート', 1, 'special_move', 1, 'Tsubasa''s signature technique involving forward spin that creates an unpredictable ball trajectory, making it extremely difficult for goalkeepers to save.', 3, 'mastered'),
('Golden Combi', 'ゴールデンコンビ', 1, 'special_move', 1, 'Perfect team combination technique with Taro Misaki, demonstrating ultimate harmony between two players.', 15, 'mastered'),
('SGGK', 'SGGK', 2, 'special_move', 1, 'Super Great Goal Keeper technique series, representing the pinnacle of goalkeeping ability with supernatural reflexes and positioning.', 5, 'mastered'),
('Rising Impact', 'ライジングインパクト', 3, 'gift', 2, 'Supernatural ability allowing perfect sweet spot contact for drives exceeding 450 yards through ideal ball compression and energy transfer.', 2, 'intermediate'),
('Shining Road', 'シャイニングロード', 4, 'gift', 2, 'Visualization ability that reveals the perfect putting path as a golden line, enabling precise putting accuracy up to 70 yards.', 5, 'mastered');

-- Insert Character Variants (Canon tier)
INSERT INTO character_variants (base_character_id, variant_type, variant_name, source_dimension_id, power_stat, speed_stat, precision_stat, harmony_stat, focus_stat, card_rarity, card_cost) VALUES 
(1, 'canon', 'Tsubasa Ozora', 1, 65, 85, 80, 100, 60, 'legendary', 8),
(2, 'canon', 'Genzo Wakabayashi', 1, 80, 95, 90, 70, 85, 'legendary', 7),
(3, 'canon', 'Gawain Nanaumi', 2, 90, 60, 65, 35, 80, 'legendary', 8),
(4, 'canon', 'Lancelot Norman', 2, 45, 55, 100, 30, 95, 'legendary', 7);

-- Insert Cards
INSERT INTO cards (card_set_id, character_variant_id, card_name, card_type, rarity, cost, flavor_text) VALUES 
(1, 1, 'Tsubasa Ozora - Soccer Prodigy', 'character', 'legendary', 8, 'The ball is my friend!'),
(1, 2, 'Genzo Wakabayashi - SGGK Legend', 'character', 'legendary', 7, 'No shot will pass through my goal!'),
(1, 3, 'Gawain Nanaumi - Country Prodigy', 'character', 'legendary', 8, 'Golf is about finding your own path.'),
(1, 4, 'Lancelot Norman - Precision Master', 'character', 'legendary', 7, 'Perfection is the only acceptable standard.');

-- Update character counts in card sets
UPDATE card_sets SET common_count = 0, uncommon_count = 0, rare_count = 0, epic_count = 0, legendary_count = 4, mythic_count = 0 WHERE id = 1;

-- Insert Content Sources for tracking
INSERT INTO content_sources (source_type, source_title, series_id, character_appearances, confidence_score) VALUES 
('manga_chapter', 'Captain Tsubasa Chapter 1-50', 1, ARRAY[1, 2], 10),
('manga_chapter', 'Rising Impact Volume 1-5', 2, ARRAY[3, 4], 10);

-- Verify Import
SELECT 
    c.name as character_name,
    cv.variant_type,
    cv.power_stat,
    cv.card_rarity,
    ca.name as academy,
    COUNT(a.id) as ability_count
FROM characters c
LEFT JOIN character_variants cv ON c.id = cv.base_character_id
LEFT JOIN character_academies cha ON c.id = cha.character_id
LEFT JOIN academies ca ON cha.academy_id = ca.id
LEFT JOIN abilities a ON c.id = a.character_id
WHERE c.id IN (1, 2, 3, 4)
GROUP BY c.id, c.name, cv.variant_type, cv.power_stat, cv.card_rarity, ca.name
ORDER BY c.id;